# -*- coding: utf-8 -*-
"""chronic_disease_pipeline_final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k6JaSjeCkHlyiHOGCCmY3yQdkwG63H69

# Chronic Disease Prediction Pipeline (Corrected & Final)
Full pipeline: upload → clean → engineer features → outlier removal → encode → split → scale → SMOTE → train → compare models → ensemble → save.

## Block 1: Load Dataset (Local)
"""

import pandas as pd
import os

filename = "synthetic_health_lifestyle.csv"
if not os.path.exists(filename):
    raise FileNotFoundError(f"'{filename}' not found. Please place the CSV file in the root workspace directory.")

df = pd.read_csv(filename)

print("Shape:", df.shape)
df.head()

"""## Block 2: Lowercase Column Names"""

df.columns = df.columns.str.lower()
print(df.columns.tolist())
df.head()

"""## Block 3: Feature Engineering — Map Exercise & Alcohol to Scores"""

df['exercise_freq'] = df['exercise_freq'].str.strip().str.lower()
df['alcohol_consumption'] = df['alcohol_consumption'].str.strip().str.lower()

exercise_map = {
    'none': 0,
    '1-2 times/week': 1,
    '3-5 times/week': 2,
    'daily': 3
}

alcohol_map = {
    'none': 0,
    'low': 1,
    'moderate': 2,
    'high': 3
}

df['exercise_score'] = df['exercise_freq'].map(exercise_map)
df['alcohol_score'] = df['alcohol_consumption'].map(alcohol_map)

print("Unmapped exercise values:", df.loc[df['exercise_score'].isna(), 'exercise_freq'].unique())
print("Unmapped alcohol values:", df.loc[df['alcohol_score'].isna(), 'alcohol_consumption'].unique())

df[['exercise_freq', 'exercise_score', 'alcohol_consumption', 'alcohol_score']].head()

"""## Block 4: Encode Categorical Variables"""

from sklearn.preprocessing import LabelEncoder

df_encoded = df.copy()

binary_map = {'yes': 1, 'no': 0}
df_encoded['smoker'] = df_encoded['smoker'].str.strip().str.lower().map(binary_map)
df_encoded['chronic_disease'] = df_encoded['chronic_disease'].str.strip().str.lower().map(binary_map)

cat_cols = ['gender', 'diet_quality']
encoders = {}

for col in cat_cols:
    le = LabelEncoder()
    df_encoded[col] = le.fit_transform(df_encoded[col].astype(str))
    encoders[col] = le

print(df_encoded[['smoker', 'chronic_disease'] + cat_cols].head())
print("\nNaN counts:\n", df_encoded.isna().sum())

"""## Block 5: Define Base Features & Target"""

drop_cols = ['id', 'chronic_disease', 'exercise_freq', 'alcohol_consumption']
feature_cols = [c for c in df_encoded.columns if c not in drop_cols]

X = df_encoded[feature_cols]
y = df_encoded['chronic_disease']

print("Features used:", feature_cols)
print("X shape:", X.shape, "| y shape:", y.shape)
print("\nTarget distribution:\n", y.value_counts())

"""## Block 6: Remove Outliers (Manual Thresholds)"""

df_clean = df_encoded.copy()

print("Rows before outlier removal:", df_clean.shape[0])

df_clean = df_clean[
    (df_clean['age'] >= 18) & (df_clean['age'] <= 82) &
    (df_clean['weight_kg'] >= 33) & (df_clean['weight_kg'] <= 150) &
    (df_clean['height_cm'] >= 135) & (df_clean['height_cm'] <= 200) &
    (df_clean['bmi'] >= 9.5) & (df_clean['bmi'] <= 50) &
    (df_clean['sleep_hours'] >= 2.5) & (df_clean['sleep_hours'] <= 12)
]

print("Rows after outlier removal:", df_clean.shape[0])

X = df_clean[feature_cols]
y = df_clean['chronic_disease']

print("\nNew X shape:", X.shape, "| y shape:", y.shape)
print("Target distribution after cleaning:\n", y.value_counts())

"""## Block 7: Custom Weighted Risk Score
NOTE: computed on `df_clean` (post outlier-removal, pre-dropna) — this ordering matters, see Block 9 fix below.
"""

df_clean['smoker_norm'] = df_clean['smoker']  # already 0/1
df_clean['exercise_norm'] = 1 - (df_clean['exercise_score'] / df_clean['exercise_score'].max())
df_clean['alcohol_norm'] = df_clean['alcohol_score'] / df_clean['alcohol_score'].max()
df_clean['sleep_norm'] = 1 - ((df_clean['sleep_hours'] - df_clean['sleep_hours'].min()) /
                               (df_clean['sleep_hours'].max() - df_clean['sleep_hours'].min()))

df_clean['risk_score'] = (
    0.4 * df_clean['smoker_norm'] +
    0.3 * df_clean['exercise_norm'] +
    0.2 * df_clean['alcohol_norm'] +
    0.1 * df_clean['sleep_norm']
)

print(df_clean[['smoker_norm', 'exercise_norm', 'alcohol_norm', 'sleep_norm', 'risk_score']].head())
print("\nRisk score stats:\n", df_clean['risk_score'].describe())

"""## Block 8: Health Rating Score (0-100 scale)"""

def bmi_penalty(bmi):
    if 18.5 <= bmi <= 24.9:
        return 0
    elif bmi < 18.5:
        return (18.5 - bmi) / 18.5
    else:
        return (bmi - 24.9) / 24.9

df_clean['bmi_penalty'] = df_clean['bmi'].apply(bmi_penalty)
df_clean['bmi_penalty'] = df_clean['bmi_penalty'].clip(0, 1)

df_clean['stress_norm'] = (df_clean['stress_level'] - df_clean['stress_level'].min()) / \
                           (df_clean['stress_level'].max() - df_clean['stress_level'].min())

df_clean['health_rating'] = 100 * (1 - (
    0.30 * df_clean['smoker_norm'] +
    0.25 * df_clean['exercise_norm'] +
    0.15 * df_clean['alcohol_norm'] +
    0.10 * df_clean['sleep_norm'] +
    0.10 * df_clean['bmi_penalty'] +
    0.10 * df_clean['stress_norm']
))

df_clean['health_rating'] = df_clean['health_rating'].clip(0, 100)

print(df_clean[['risk_score', 'health_rating']].describe())
df_clean[['smoker_norm', 'exercise_norm', 'alcohol_norm', 'sleep_norm', 'bmi_penalty', 'stress_norm', 'health_rating']].head()

"""## Block 9: Fix NaNs in Engineered Features (CORRECTED — no dropna trap)
**This is the fix for the bug found earlier**: instead of dropping ~44% of rows, we fill unmapped `exercise_score`/`alcohol_score` values with the median and recompute the derived scores — while keeping the full row count.
"""

cols_to_check = ['smoker_norm', 'exercise_norm', 'alcohol_norm', 'sleep_norm',
                  'bmi_penalty', 'stress_norm', 'risk_score', 'health_rating']

print("NaN counts BEFORE fix:\n", df_clean[cols_to_check].isna().sum())

# Fill unmapped exercise/alcohol scores with median (do NOT dropna — that silently deletes ~44% of rows)
df_clean['exercise_score'] = df_clean['exercise_score'].fillna(df_clean['exercise_score'].median())
df_clean['alcohol_score'] = df_clean['alcohol_score'].fillna(df_clean['alcohol_score'].median())

# Recompute normalized + derived scores now that inputs are clean
df_clean['exercise_norm'] = 1 - (df_clean['exercise_score'] / df_clean['exercise_score'].max())
df_clean['alcohol_norm'] = df_clean['alcohol_score'] / df_clean['alcohol_score'].max()

df_clean['risk_score'] = (
    0.4 * df_clean['smoker_norm'] +
    0.3 * df_clean['exercise_norm'] +
    0.2 * df_clean['alcohol_norm'] +
    0.1 * df_clean['sleep_norm']
)

df_clean['health_rating'] = 100 * (1 - (
    0.30 * df_clean['smoker_norm'] +
    0.25 * df_clean['exercise_norm'] +
    0.15 * df_clean['alcohol_norm'] +
    0.10 * df_clean['sleep_norm'] +
    0.10 * df_clean['bmi_penalty'] +
    0.10 * df_clean['stress_norm']
))
df_clean['health_rating'] = df_clean['health_rating'].clip(0, 100)

print("\nNaN counts AFTER fix:\n", df_clean[cols_to_check].isna().sum())
print("\nRows retained:", df_clean.shape[0], "(should match post-outlier-removal count, NOT reduced further)")

"""## Block 10: Validate risk_score & health_rating Against Target"""

print("=== risk_score ===")
print("Mean for chronic_disease=1:", df_clean.loc[df_clean['chronic_disease']==1, 'risk_score'].mean())
print("Mean for chronic_disease=0:", df_clean.loc[df_clean['chronic_disease']==0, 'risk_score'].mean())
print("Correlation with target:", df_clean[['risk_score', 'chronic_disease']].corr().iloc[0, 1])

print("\n=== health_rating ===")
print("Mean for chronic_disease=1:", df_clean.loc[df_clean['chronic_disease']==1, 'health_rating'].mean())
print("Mean for chronic_disease=0:", df_clean.loc[df_clean['chronic_disease']==0, 'health_rating'].mean())
print("Correlation with target:", df_clean[['health_rating', 'chronic_disease']].corr().iloc[0, 1])

"""## Block 11: Rebuild Feature Set with risk_score & health_rating"""

feature_cols_v2 = feature_cols + ['risk_score', 'health_rating']

X = df_clean[feature_cols_v2]
y = df_clean['chronic_disease']

print("Updated feature columns:", feature_cols_v2)
print("X shape:", X.shape, "| y shape:", y.shape)
print("NaN check in final X:", X.isna().sum().sum())

"""## Block 12: Correlation of ALL Features with Target"""

print("=== ALL FEATURES CORRELATION WITH TARGET ===")
print(X.assign(target=y).corr()['target'].sort_values(ascending=False))

"""## Block 13: Train/Test Split"""

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print("X_train:", X_train.shape, "X_test:", X_test.shape)
print("y_train distribution:\n", y_train.value_counts())
print("y_test distribution:\n", y_test.value_counts())

"""## Block 14: Feature Scaling"""

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print("Scaled train shape:", X_train_scaled.shape)
print("NaN check:", pd.DataFrame(X_train_scaled).isna().sum().sum())

"""## Block 15: Baseline Random Forest (No SMOTE)"""

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

model = RandomForestClassifier(
    n_estimators=200,
    class_weight='balanced',
    random_state=42
)
model.fit(X_train_scaled, y_train)

y_pred = model.predict(X_test_scaled)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred, zero_division=0))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

"""## Block 16: ROC Curve & AUC (Baseline Model)"""

from sklearn.metrics import roc_curve, roc_auc_score
import matplotlib.pyplot as plt

y_proba = model.predict_proba(X_test_scaled)[:, 1]
auc_score = roc_auc_score(y_test, y_proba)
fpr, tpr, thresholds = roc_curve(y_test, y_proba)

plt.figure(figsize=(6, 5))
plt.plot(fpr, tpr, label=f'ROC Curve (AUC = {auc_score:.3f})')
plt.plot([0, 1], [0, 1], linestyle='--', color='gray')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve — Baseline Model')
plt.legend()
# plt.show()

print("AUC Score:", auc_score)

"""## Block 17: SMOTE Oversampling"""

# !pip install -q imbalanced-learn

from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=42)
X_train_resampled, y_train_resampled = smote.fit_resample(X_train_scaled, y_train)

print("Before SMOTE:", y_train.value_counts().to_dict())
print("After SMOTE:", pd.Series(y_train_resampled).value_counts().to_dict())

"""## Block 18: Retrain Random Forest on SMOTE-Balanced Data"""

model_v2 = RandomForestClassifier(n_estimators=200, random_state=42)
model_v2.fit(X_train_resampled, y_train_resampled)

y_pred_v2 = model_v2.predict(X_test_scaled)

print("Accuracy:", accuracy_score(y_test, y_pred_v2))
print("\nClassification Report:\n", classification_report(y_test, y_pred_v2, zero_division=0))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_v2))

"""## Block 19: Threshold Tuning"""

import numpy as np
from sklearn.metrics import f1_score

y_proba_v2 = model_v2.predict_proba(X_test_scaled)[:, 1]

best_threshold = 0.5
best_f1 = 0

for t in np.arange(0.1, 0.9, 0.05):
    preds = (y_proba_v2 >= t).astype(int)
    f1 = f1_score(y_test, preds, zero_division=0)
    if f1 > best_f1:
        best_f1 = f1
        best_threshold = t

print(f"Best threshold: {best_threshold:.2f}, Best F1: {best_f1:.4f}")

y_pred_tuned = (y_proba_v2 >= best_threshold).astype(int)
print("\nClassification Report at Best Threshold:\n", classification_report(y_test, y_pred_tuned, zero_division=0))

"""## Block 20: Feature Importance (v2)"""

importances_v2 = pd.Series(model_v2.feature_importances_, index=feature_cols_v2).sort_values(ascending=False)
print("Feature Importances (v2):\n", importances_v2)

importances_v2.plot(kind='barh', figsize=(8, 6), title='Feature Importance (with Risk Score & Health Rating)')

"""## Block 21: Install XGBoost, LightGBM, CatBoost"""

# !pip install -q xgboost lightgbm catboost

"""## Block 22: Compare Multiple Models"""

from sklearn.linear_model import LogisticRegression
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from catboost import CatBoostClassifier
from sklearn.metrics import precision_score, recall_score

models = {
    'Logistic Regression': LogisticRegression(class_weight='balanced', max_iter=1000, random_state=42),
    'Random Forest': RandomForestClassifier(n_estimators=200, class_weight='balanced', random_state=42),
    'XGBoost': XGBClassifier(eval_metric='logloss', random_state=42),
    'LightGBM': LGBMClassifier(random_state=42, verbose=-1),
    'CatBoost': CatBoostClassifier(verbose=0, random_state=42)
}

results = []

for name, clf in models.items():
    clf.fit(X_train_resampled, y_train_resampled)
    preds = clf.predict(X_test_scaled)
    proba = clf.predict_proba(X_test_scaled)[:, 1]

    results.append({
        'Model': name,
        'Accuracy': accuracy_score(y_test, preds),
        'Precision': precision_score(y_test, preds, zero_division=0),
        'Recall': recall_score(y_test, preds, zero_division=0),
        'F1': f1_score(y_test, preds, zero_division=0),
        'AUC': roc_auc_score(y_test, proba)
    })

results_df = pd.DataFrame(results).sort_values('F1', ascending=False)
print(results_df)

"""## Block 23: Visualize Model Comparison"""

metrics_to_plot = ['Accuracy', 'Precision', 'Recall', 'F1', 'AUC']

fig, ax = plt.subplots(figsize=(10, 6))
results_df.set_index('Model')[metrics_to_plot].plot(kind='bar', ax=ax)
plt.title('Model Comparison Across Metrics')
plt.ylabel('Score')
plt.xticks(rotation=45)
plt.legend(loc='lower right')
plt.tight_layout()
# plt.show()

"""## Block 24: ROC Curves for All Models"""

plt.figure(figsize=(8, 6))

for name, clf in models.items():
    proba = clf.predict_proba(X_test_scaled)[:, 1]
    fpr, tpr, _ = roc_curve(y_test, proba)
    auc = roc_auc_score(y_test, proba)
    plt.plot(fpr, tpr, label=f'{name} (AUC={auc:.3f})')

plt.plot([0, 1], [0, 1], linestyle='--', color='gray', label='Random')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curves — Model Comparison')
plt.legend()
# plt.show()

"""## Block 25: Confusion Matrices Grid (All Models)"""

import seaborn as sns

fig, axes = plt.subplots(1, len(models), figsize=(20, 4))

for ax, (name, clf) in zip(axes, models.items()):
    preds = clf.predict(X_test_scaled)
    cm = confusion_matrix(y_test, preds)
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', ax=ax, cbar=False)
    ax.set_title(name)
    ax.set_xlabel('Predicted')
    ax.set_ylabel('Actual')

plt.tight_layout()
# plt.show()

"""## Block 26: Weighted Voting Ensemble (RF + XGBoost + CatBoost)"""

from sklearn.ensemble import VotingClassifier

rf_clf = models['Random Forest']
xgb_clf = models['XGBoost']
cat_clf = models['CatBoost']

ensemble = VotingClassifier(
    estimators=[
        ('rf', rf_clf),
        ('xgb', xgb_clf),
        ('cat', cat_clf)
    ],
    voting='soft',
    weights=[0.4, 0.3, 0.3]
)

ensemble.fit(X_train_resampled, y_train_resampled)

y_pred_ens = ensemble.predict(X_test_scaled)
y_proba_ens = ensemble.predict_proba(X_test_scaled)[:, 1]

print("Ensemble Accuracy:", accuracy_score(y_test, y_pred_ens))
print("Ensemble AUC:", roc_auc_score(y_test, y_proba_ens))
print("\nClassification Report:\n", classification_report(y_test, y_pred_ens, zero_division=0))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_ens))

"""## Block 27: Threshold Tuning on Ensemble"""

best_threshold_ens = 0.5
best_f1_ens = 0

for t in np.arange(0.1, 0.9, 0.05):
    preds = (y_proba_ens >= t).astype(int)
    f1 = f1_score(y_test, preds, zero_division=0)
    if f1 > best_f1_ens:
        best_f1_ens = f1
        best_threshold_ens = t

print(f"Best threshold: {best_threshold_ens:.2f}, Best F1: {best_f1_ens:.4f}")

y_pred_ens_tuned = (y_proba_ens >= best_threshold_ens).astype(int)
print("\nClassification Report at Best Threshold:\n", classification_report(y_test, y_pred_ens_tuned, zero_division=0))

"""## Block 28: Final Comparison Table (All Models + Ensemble)"""

final_results = results_df.copy()

final_results = pd.concat([
    final_results,
    pd.DataFrame([{
        'Model': 'Weighted Ensemble (RF+XGB+CatBoost)',
        'Accuracy': accuracy_score(y_test, y_pred_ens_tuned),
        'Precision': precision_score(y_test, y_pred_ens_tuned, zero_division=0),
        'Recall': recall_score(y_test, y_pred_ens_tuned, zero_division=0),
        'F1': best_f1_ens,
        'AUC': roc_auc_score(y_test, y_proba_ens)
    }])
], ignore_index=True)

print(final_results.sort_values('F1', ascending=False))

"""## Block 29: Final Summary — Metrics + Correlation Together
This documents the honest finding: near-zero feature-target correlation caps model performance regardless of technique used.
"""

print("="*50)
print("FINAL MODEL SUMMARY")
print("="*50)
print(f"Model: Weighted Ensemble (RF+XGB+CatBoost) + SMOTE + Threshold Tuning")
print(f"Best Threshold: {best_threshold_ens:.2f}")
print(f"Accuracy: {accuracy_score(y_test, y_pred_ens_tuned):.4f}")
print(f"F1 Score (class 1): {best_f1_ens:.4f}")
print(f"AUC Score: {roc_auc_score(y_test, y_proba_ens):.4f}")
print("\nClassification Report:\n", classification_report(y_test, y_pred_ens_tuned, zero_division=0))

print("="*50)
print("CORRELATION ANALYSIS (WHY PERFORMANCE IS CAPPED)")
print("="*50)
corr_summary = X.assign(target=y).corr()['target'].sort_values(ascending=False)
print(corr_summary)
print(f"\nMax absolute correlation: {corr_summary.drop('target').abs().max():.4f}")
print("Conclusion: No feature shows meaningful correlation (all |r| < 0.03),")
print("indicating chronic_disease was likely generated independently of these features.")

"""## Block 30: Save Final Ensemble Model & Scaler"""

import joblib

joblib.dump(ensemble, 'chronic_disease_ensemble_model.pkl')
joblib.dump(scaler, 'scaler.pkl')

print("Ensemble model and scaler saved successfully.")

# Files are saved directly to the local directory, so no colab download helper is needed.